In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/gitpractice/geultin/brunch_df.csv")

In [ ]:
data

,Unnamed: 0,0,1
0,0,16. 매일 글을 써서 좋은 점,긴 글은 아니지만 매일 글을 쓰고 있다. 글을 쓰니 좋은 점들이 있다. 동영상 보는...
1,1,유메토 마보로시,"인상 깊었다. 커다란 흰 소와 함께 거닐던 남자가 있었는데, 그 둘은 강 앞의 벤..."
2,2,슬픔을 잊기 위해 감정을 버렸다 (2편),"#4. 의도의 파악 달리기를 시작하기 전, 앞서 근원에 대한 이야기를 해보자. 열..."
3,3,소고기 미역국,"먹거리가 흔한 현대사회에서도 대접받는 메뉴는 따로 있다. 산에서 나는 송이, 바다에..."
4,4,전라도를 지켜라,호남 곧 전라도는 곡창지대다. 일본의 도요도미도 그것을 알았는지 ‘전라도를 점령하라...
...,...,...,...
4457,4433,인생은 작은 수필,하얀 종이 냄새가 나는 새 노트 첫장에 글을 쓰는 건 망설여진다.순백의 깨끗함을 더...
4458,4434,01화 기억의 시작,"어릴적, 할아버지 할머니와 함께 사는 대가족이었다.할아버지, 할머니, 부모님, 딸 ..."
4459,4435,꿈틀거리는 것들을 감싸 안는 것,책을 고르다 보면 소설보다 먼저 수필을 찾는 날 발견하게 된다. 인간정신의 총 집약...
4460,4436,기억과 마주하다...,"생후 16개월. 난 그때부터 아팠다.내 일생을 흔들어버린 찰나의 순간과,함께하지 않..."
4461,4437,"언제부터였을까,","언제부터였을까,돌아오지 않을 젊은 시절을 화려하고 다채롭게 살고 싶다는 마음보다,..."

In [ ]:
data= data[['0','1']]

In [ ]:
data

,0,1
0,16. 매일 글을 써서 좋은 점,긴 글은 아니지만 매일 글을 쓰고 있다. 글을 쓰니 좋은 점들이 있다. 동영상 보는...
1,유메토 마보로시,"인상 깊었다. 커다란 흰 소와 함께 거닐던 남자가 있었는데, 그 둘은 강 앞의 벤..."
2,슬픔을 잊기 위해 감정을 버렸다 (2편),"#4. 의도의 파악 달리기를 시작하기 전, 앞서 근원에 대한 이야기를 해보자. 열..."
3,소고기 미역국,"먹거리가 흔한 현대사회에서도 대접받는 메뉴는 따로 있다. 산에서 나는 송이, 바다에..."
4,전라도를 지켜라,호남 곧 전라도는 곡창지대다. 일본의 도요도미도 그것을 알았는지 ‘전라도를 점령하라...
...,...,...
4457,인생은 작은 수필,하얀 종이 냄새가 나는 새 노트 첫장에 글을 쓰는 건 망설여진다.순백의 깨끗함을 더...
4458,01화 기억의 시작,"어릴적, 할아버지 할머니와 함께 사는 대가족이었다.할아버지, 할머니, 부모님, 딸 ..."
4459,꿈틀거리는 것들을 감싸 안는 것,책을 고르다 보면 소설보다 먼저 수필을 찾는 날 발견하게 된다. 인간정신의 총 집약...
4460,기억과 마주하다...,"생후 16개월. 난 그때부터 아팠다.내 일생을 흔들어버린 찰나의 순간과,함께하지 않..."
4461,"언제부터였을까,","언제부터였을까,돌아오지 않을 젊은 시절을 화려하고 다채롭게 살고 싶다는 마음보다,..."

In [ ]:
  import pandas as pd

  data = [['행복','저는 행복한 사람입니다'],['참여 후기','밤샘 대회(북커톤)는 재미있지만 힘들다.'],['자기소개','안녕하세요 저는 북흐북흐 팀입니다.'],['날','작업을 하다보니 벌써 날이 밝앗다ㅠㅠㅠ'],['간식', '내가좋아하는간식은 초코파이다★']]

  df = pd.DataFrame(data, columns=['title','content'])

df

   title                 content
0     행복            저는 행복한 사람입니다
1  참여 후기  밤샘 대회(북커톤)는 재미있지만 힘들다.
2   자기소개     안녕하세요 저는 북흐북흐 팀입니다.
3      날   작업을 하다보니 벌써 날이 밝앗다ㅠㅠㅠ
4     간식        내가좋아하는간식은 초코파이다★

In [ ]:
# #파일로 저장 (주피터사용)

# data= data[['title','content']]
# data

# for i in range(5):    
#     f = open("oh18_txt_{}.txt".format(i), 'w', encoding='utf-8')
#     content = data.iloc[i,1].strip()
#     f.write(content)
#     f.close()

KeyError: ignored

In [ ]:
# data.to_csv("글틴csv",encoding='utf-8')

In [ ]:
!pip install git+https://github.com/ssut/py-hanspell.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/ssut/py-hanspell.git
  Cloning https://github.com/ssut/py-hanspell.git to /tmp/pip-req-build-z7h6phxl
  Running command git clone --filter=blob:none --quiet https://github.com/ssut/py-hanspell.git /tmp/pip-req-build-z7h6phxl
  Resolved https://github.com/ssut/py-hanspell.git to commit 8e993cf46f97f9d665c15633a0fc78ac1b727713
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from py-hanspell==1.1) (2.25.1)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->py-hanspell==1.1) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->py-hanspell==1.1) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->py-hanspell==1.1) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->py-hanspell==1.1) (1.24.3)

In [ ]:
banned_title_list = ['장원','필독','공지','글틴']
banned_content_list=['저는 ', '제가 ', '습니다', '입니다']

banned_index = []
for i in range(len(data)):
    for word in banned_title_list:
        if word in str(data.iloc[i,1]):
            banned_index.append(i)
            # print(data.iloc[i,1])
            break
            
    for word in banned_content_list:
        if word in df.iloc[i,1]:
            banned_index.append(i)
            break

newframe= df.drop(index=banned_index, axis=0)
newframe= newframe.reset_index(drop=True)

newframe

   title                 content
0  참여 후기  밤샘 대회(북커톤)는 재미있지만 힘들다.
1      날   작업을 하다보니 벌써 날이 밝앗다ㅠㅠㅠ
2     간식        내가좋아하는간식은 초코파이다★

In [ ]:
df

   title                content
0     행복           저는 행복한 사람입니다
1  참여 후기    북커톤(4회)은 재미있지만 힘들다.
2   자기소개    안녕하세요 저는 북흐북흐 팀입니다.
3      날  작업을 하다보니 벌써 날이 밝앗다ㅠㅠㅠ
4     간식       내가좋아하는간식은 초코파이다★

In [ ]:
import re
from hanspell import spell_checker
li = ["출처","약력","발행일"]


for i in range(len(newframe)):
    
    k = newframe.loc[i,'content']
    
    # 정규표현식을 이용한 1차 전처리
    k = re.sub(r"(http|https)?:\/\/\S+\b|www\.(\w+\.)+\S*", '', k)# url주소 제거
    k = re.sub("[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$']", '',k)#이메일제거
    k = re.sub('[0-9]{4}년 [0-9]{,2}월 [0-9]{,2}일','',k) #날짜 제거
    k = re.sub('[0-9]{4}년 [0-9]{,2}월','',k) #날짜 제거
    k = re.sub('[0-9]{4}. [0-9]{,2}. [0-9]{,2}','',k) #날짜 제거
    k = re.sub(r"\([^)]*\)",'',k) #() 안, () 제거
    k = re.sub(r"\[[^)]*\]",'',k) #[] 안, [] 제거
    k = re.sub(r"\<[^)]*\>",'',k) #[] 안, [] 제거
    k = re.sub('[ぁ-ゔァ-ヴー々〆〤一-龥]','',k) #한자, 일본어 제거 
    k = re.sub('[ㄱ-ㅎㅏ-ㅣ]+','',k) #자음, 모음 제거
    k = re.sub('“','"',k) #큰 따옴표 통일
    k = re.sub('”','"',k)
    k = re.sub('‘',"'",k) #작은 따옴표 통일
    k = re.sub('’',"'",k)
    k = re.sub('[^가-힣 0-9 a-z A-Z \. \, \' \" \? \! ]+','',k) #특수문자 제거
    
    newframe.loc[i,'content'] = k
 
    
    new=""

    k=k.replace(".",".#")
    k=k.replace("?","?#")
    k=k.replace("!","!#")
    
    sen_list = [x.strip() for x in k.split("#")]
    for sen in sen_list:
        if sen.startswith("이 글은") and sen.endswith("밝혀 둡니다."):
    k= spell_checker.check(k).as_dict()['checked']
        a= any(keyword in new_sen for keyword in li) #특정 키워드(리스트 li에) 찾아서 제거
        if a is True:
            continue
        else:
            new = new +" " + new_sen
    print(new)
    newframe.loc[i,'content'] = k

newframe

   title              content
0  참여 후기    밤샘 대회는 재미있지만 힘들다.
1      날  작업을 하다 보니 벌써 날이 밝았다
2     간식    내가 좋아하는 간식은 초코파이다

In [ ]:
newframe

In [ ]:
newframe.to_csv("brunch1.csv",index=False, encoding='utf-8-sig')

In [ ]:
for i in range(len(newframe)):    
    f = open("x_txt_{}.txt".format(i), 'w', encoding='utf-8')
    data = newframe.iloc[i,1].strip()
    f.write(data)
    f.close()

In [ ]:
print('?'=='?')

True

In [ ]:
['비전','계획','미래','용기','도전','희망','성장','발전','성공','변화','해방','마무리','앞으로','기대','느낀점', '수상','경험','보완']